phrase = '   I love Curso em Vídeo!   '

print(phrase.replace('Curso em Vídeo', 'Studying Python'))
print(len(phrase))
print(phrase.split())
print('-'.join(phrase.split()))
print(phrase.upper())
print(phrase.lower())
print(phrase.capitalize())
print(phrase.title())
print(phrase.strip())
print(phrase.count(' '))
print(phrase.find('Vídeo'))
print('Curso' in phrase)
print(phrase.startswith(' '))
print(phrase.endswith('!'))
print(phrase.partition(' '))
print(phrase.swapcase())
print(phrase.translate(str.maketrans('áéíóú', 'aeiou')))
print(phrase.center(50, '*'))
print(phrase.lstrip())
print(phrase.rstrip())
print(phrase.zfill(40))
